/* ============================================================
   data.js — site configuration + calendar seed data
   Loaded as a plain classic script (no import/export) so the
   site works by double-clicking index.html — ES modules are
   blocked by browsers when loaded from a file:// URL.
   ============================================================ */

// Local admin password, used when the site is opened directly
// (file:// or Live Server) with no backend available.
// When deployed to Vercel, /api/login checks the real
// ADMIN_PASSWORD environment variable instead — this local
// value is only a fallback for offline / local-file use.
const APP_CONFIG = {
  LOCAL_ADMIN_PASSWORD: 'demo123',
  CALENDAR_STORAGE_KEY: 'pmvikas_calendar_v1',
};

// Seed content for the PM-VIKAS activity calendar, exactly as
// logged by the intern. Used as the starting dataset and as the
// fallback shown the very first time no saved data exists yet
// (in Vercel KV, or in this browser's local storage).
const DEFAULT_CALENDAR_LOG = {
  '2026-06-19': { title: 'Introduction to IoT & Ecosystem', module: 'Electronics', description: 'Inauguration of the PM-VIKAS IoT assistant training program. Introduced to IoT nodes, device-to-cloud architectures, real-world smart systems (cities, grid networks), and communication layers.' },
  '2026-06-20': { title: 'Microcontroller Architectures & IDE', module: 'Electronics', description: 'Study of Arduino Uno and ESP32 board layouts. Installation of Arduino IDE software, configuring port selections, writing basic C script routines, and flashing standard status LED programs.' },
  '2026-06-22': { title: 'Basic Electronic Components', module: 'Electronics', description: 'Detailed analysis of electronic devices including Resistors, Capacitors, and Light Emitting Diodes (LEDs). Practical hands-on breadboard wiring configurations and simple circuit design rules.' },
  '2026-06-23': { title: 'Hardware Measurement & GPIOs', module: 'Electronics', description: 'Configuring and testing digital/analog General Purpose Input/Output (GPIO) pins. Measuring voltage, loop currents, and resistance values across wired test circuits using a digital multimeter.' },
  '2026-06-24': { title: 'Interfacing LDR (Light Sensors)', module: 'IoT Projects', description: 'Interfacing Light Dependent Resistors (LDR) to read changing analog light intensity levels. Programmed thresholds to trigger output alerts based on ambient illumination changes.' },
  '2026-06-25': { title: 'Interfacing DHT11 Temperature Sensor', module: 'IoT Projects', description: 'Interfacing the DHT11 sensor to monitor environmental temperature and humidity levels. Written data validation logic to filter out noise fluctuations and format values for transmission.' },
  '2026-06-26': { title: 'ESP32 Wi-Fi & Network Protocols', module: 'Networking', description: "Setting up the ESP32 microcontroller's Wi-Fi module. Establishing station (STA) connections to local networks and checking communication protocols (IP addressing, TCP client/server models)." },
  '2026-06-27': { title: 'Blynk IoT Cloud Setup & Auth', module: 'Networking', description: 'Created developer accounts on Blynk IoT Cloud. Set up device templates, virtual datastreams, and generated secure Authentication Tokens. Configured basic mobile application dashboards.' },
  '2026-06-29': { title: 'Real-time Cloud Telemetry (Blynk)', module: 'IoT Projects', description: 'Programmed the ESP32 to upload environmental parameters (LDR intensity and DHT11 values) to the Blynk Cloud dashboard in real-time. Verified low-latency response and remote app widgets.' },
  '2026-06-30': { title: 'ThingSpeak Logger & Capstone', module: 'IoT Projects', description: 'Linked the ESP32 to the ThingSpeak server for long-term data logging and visualization. Assembled the final Capstone Project: an integrated Smart Home System that tracks sensors and controls output relays.' },

  '2026-07-01': { title: 'Absent', module: '', status: 'absent', description: 'No internship activities were conducted on this day due to absence.' },
  '2026-07-02': { title: 'Absent', module: '', status: 'absent', description: 'No internship activities were conducted on this day due to absence.' },
  '2026-07-03': { title: 'Day 13: IEEE Paper Survey & Project Domain Exploration', module: 'Research', description: 'Conducted a comprehensive literature survey using Google Scholar and the IEEE Xplore Digital Library to explore potential project domains. Studied recent research papers to understand emerging technological trends, identify research gaps, and evaluate innovative solutions across various fields. Analyzed research abstracts, methodologies, proposed architectures, datasets, and future research directions to determine suitable areas for project development. Learned effective techniques for academic paper searching using relevant keywords, publication filters, and citation analysis. This activity provided valuable insights into selecting an appropriate project domain and established a strong foundation for future research-oriented project development.' },
  '2026-07-04': { title: 'Day 14: IEEE Paper Analysis & Project Domain Finalization', module: 'Research', description: 'Continued the literature survey by performing an in-depth analysis of shortlisted IEEE research papers related to the selected project domains. Compared methodologies, implementation techniques, system architectures, datasets, and performance evaluation metrics to understand the strengths and limitations of existing solutions. Identified research gaps and discussed feasible approaches for developing an innovative project. Organized the collected literature for future reference and finalized the project domain after evaluating the novelty, practicality, and research potential of different ideas.' },
  '2026-07-06': { title: 'Day 15: Networking Fundamentals & Cisco Packet Tracer', module: 'Networking', description: 'Explored the fundamentals of computer networking, including networking concepts, internetworking, the OSI and TCP/IP models, IPv4 and IPv6 addressing, subnetting, and network communication. Gained hands-on experience using Cisco Packet Tracer by establishing wired connections between devices using Copper Cross-Over cables, configuring network settings, and verifying communication through successful connectivity tests. Also learned about different network cable types and their practical applications while brainstorming innovative IoT-based project ideas for the MSME Hackathon 6.0.' },
  '2026-07-07': { title: 'Day 16: DHCP Configuration & LAN Simulation in Cisco Packet Tracer', module: 'Networking', description: 'Configured a Local Area Network (LAN) using Cisco Packet Tracer by connecting servers, switches, hubs, and multiple end devices. Implemented Dynamic Host Configuration Protocol (DHCP) to automatically assign IP addresses while configuring the server with a static IP address. Performed network connectivity verification through successful ping tests between multiple devices. This practical session strengthened understanding of IP addressing, subnet masks, DHCP configuration, and LAN communication.' },
  '2026-07-08': { title: 'Day 17: Router Configuration & Inter-Network Communication', module: 'Networking', description: "Reviewed the previous day's DHCP-based LAN implementation and advanced to router configuration using Cisco Packet Tracer. Explored FastEthernet and GigabitEthernet interfaces, configured routers for inter-network communication, and implemented both static and dynamic IP addressing. Designed a multi-router topology consisting of routers, switches, hubs, and end devices to establish communication between different networks. Successfully verified routing and connectivity across multiple subnets, improving practical knowledge of routing concepts and network design." },
  '2026-07-09': { title: 'Day 18: IoT Network Integration using Cisco Packet Tracer', module: 'Networking', description: 'Focused on integrating IoT devices using Cisco Packet Tracer by configuring routers with static routing to establish communication between multiple LANs. Connected remote computers to an IoT server and verified successful communication through ping tests. Identified and resolved routing and default gateway issues while validating remote monitoring and control of IoT devices using the IoT Monitor interface. This session strengthened practical skills in IoT networking and device connectivity.' },
  '2026-07-10': { title: 'Day 19: MSME Hackathon 6.0 Idea Submission', module: 'Hackathon', description: 'Dedicated the day to researching innovative and cost-effective solutions for MSME Hackathon 6.0. Explored various problem statements, conducted prior-art and patent searches using the WIPO PatentScope database, and evaluated existing technologies. Finalized the project concept "Automated Coconut Grading System using Computer Vision." The activity enhanced understanding of innovation, intellectual property research, and practical problem-solving for industrial applications.' },
  '2026-07-13': { title: 'Day 20: Cloud Computing & Go Services', module: 'Cloud Computing', description: 'Learned the fundamentals of Cloud Computing, including cloud service models such as Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS) along with their practical applications. Created and activated an AWS Cloud account with learning credits for hands-on practice. Installed and configured the Go (Golang) programming language and developed multiple Go-based web services, including Hello World, Calculator, Greeting API, Square Number Generator, Temperature Converter, and Weather Prediction services. Successfully tested the applications locally using localhost, gaining practical exposure to Go web development and cloud computing concepts.' },
  '2026-07-14': { title: 'Day 21: Docker & Virtualization', module: 'Cloud Computing', description: 'Learned the fundamentals of Docker and virtualization, including Docker Images, Containers, Dockerfiles, Docker Hub, and essential Docker commands. Studied the differences between traditional Virtual Machines and container-based virtualization. Created accounts for VMware and Tinkercad to support practical learning and simulation-based exercises. Gained a clear understanding of containerization, virtualization technologies, and their importance in modern cloud application deployment.' },
  '2026-07-15': { title: 'Absent', module: '', status: 'absent', description: 'No internship activities were conducted on this day due to absence.' },
  '2026-07-16': { title: 'Day 23: AWS EC2, Docker Deployment & Industry Institution Interactive Meet (IIIM)', module: 'Cloud Computing', description: 'Focused on cloud deployment and containerization by creating an Amazon EC2 Ubuntu Free Tier instance on AWS and configuring Docker for application deployment. Built Docker images and prepared previously developed Go web services for deployment using custom Dockerfiles. In the afternoon, attended the Industry Institution Interactive Meet (IIIM) organized by IIIT Kottayam in collaboration with the Board of Apprenticeship Training (BOAT), Chennai, under the Ministry of Education, Government of India. The session provided valuable insights into the National Apprenticeship Training Scheme (NATS 2.0), industry expectations, employability skills, and opportunities for industry-academia collaboration.' },
  '2026-07-17': { title: 'Day 24: IoT Fundamentals, MQTT & Tinkercad Circuit Simulations', module: 'IoT Projects', description: 'Continued learning IoT and Cloud Computing fundamentals with an introduction to the MQTT (Message Queuing Telemetry Transport) protocol and its role in lightweight communication between IoT devices. Performed hands-on circuit simulations in Tinkercad, including LED blinking using Arduino Uno, Temperature Sensor interfacing, and PIR Motion Sensor implementation. These activities strengthened understanding of Arduino programming, sensor interfacing, and virtual circuit simulation for IoT applications.' },
  '2026-07-18': { title: 'Day 25: Docker Services Development and Practical Task Completion', module: 'Cloud Computing', description: 'Successfully completed Docker-based service development and additional practical assignments. Built, tested, and executed multiple containerized applications while practicing Docker image creation, container management, and deployment techniques. Improved troubleshooting, debugging, and practical software deployment skills through hands-on exercises.' },
  '2026-07-20': { title: 'Day 26: Tinkercad IoT Circuit Design – Sensors and Actuators', module: 'IoT Projects', description: 'Designed and simulated 10 sensor-based and 10 actuator-based Arduino circuits using Tinkercad and Arduino Uno. Interfaced a variety of IoT sensors and actuators, implemented Arduino programs, and verified outputs through simulation. The activities strengthened practical knowledge of circuit design, sensor integration, actuator control, Arduino programming, and IoT application development while improving overall hardware interfacing skills.' },
};

const MODULE_LABELS = {
  'Electronics': 'Electronics',
  'Networking': 'Networking',
  'Arduino Programming': 'Arduino Programming',
  'IoT Projects': 'Hands-on IoT Projects',
  'Research': 'Research & Literature Survey',
  'Hackathon': 'MSME Hackathon 6.0',
  'Cloud Computing': 'Cloud Computing',
};
